// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSVz-7rcgfjL3M9-1qw3HHYocMT1fUOM8',
    appId: '1:657797516641:web:5392926893554f287b8920',
    messagingSenderId: '657797516641',
    projectId: 'route-bkk',
    authDomain: 'route-bkk.firebaseapp.com',
    storageBucket: 'route-bkk.firebasestorage.app',
    measurementId: 'G-7P39HGYY8Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClLkFzPrn-rSrKkhjewYV2Ebbq84c5Vb4',
    appId: '1:657797516641:android:b090d6581e1c8ced7b8920',
    messagingSenderId: '657797516641',
    projectId: 'route-bkk',
    storageBucket: 'route-bkk.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJlBl-72kyiAdZkdZLpv8Cn5Y7VEfCsLQ',
    appId: '1:657797516641:ios:c7ba0cafce1f514c7b8920',
    messagingSenderId: '657797516641',
    projectId: 'route-bkk',
    storageBucket: 'route-bkk.firebasestorage.app',
    iosBundleId: 'com.hugekc.routetransit',
  );
}
